---
volumes:
  freezing-data:
    external: true

services:

  freezing-db:
    image: mysql:8.0
    container_name: freezing-db-dev
    ports:
      - "3306:${MYSQL_PORT:-3306}"
    volumes:
      - freezing-data:/var/lib/mysql
      - ./docker/db/sql-scripts:/sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-fr33z3}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-freezing}
      MYSQL_USER: ${MYSQL_USER:-freezing}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-zeer0}

  freezing-web:
    build: .
    container_name: freezing-web-dev
    ports:
      - "5000:${FREEZING_WEB_PORT:-8000}"
    volumes:
      - ./data/cache:/data/cache
      - ./leaderboards:/data/leaderboards
      - ./data/sessions:/data/sessions
      - ./resources/docker/settings.cfg:/config/settings.cfg
    environment:
      BIND_INTERFACE: "0.0.0.0"
      VIRTUAL_HOST: ${FREEZING_WEB_FQDN}
      LETSENCRYPT_HOST: ${FREEZING_WEB_FQDN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      SQLALCHEMY_URL: ${SQLALCHEMY_URL}
      BEANSTALKD_HOST: beanstalkd.container
      BEANSTALKD_PORT: 11300
      STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}
      STRAVA_CLIENT_SECRET: ${STRAVA_CLIENT_SECRET}
      TEAMS: ${TEAMS}
      OBSERVER_TEAMS: ${OBSERVER_TEAMS}
      MAIN_TEAM: ${MAIN_TEAM}
      START_DATE: ${START_DATE}
      END_DATE: ${END_DATE}
      TIMEZONE: ${TIMEZONE:-America/New_York}
      COMPETITION_TITLE: ${COMPETITION_TITLE:-Freezing Saddles Local Dev}
