---
version: '3'

volumes:
  freezing-data:
    external: true

services:

  freezing-db:
    image: mysql:5.6
    container_name: freezing-db
    ports:
      - "3306:3306"
    volumes:
      - freezing-data:/var/lib/mysql
      - ./docker/db/sql-scripts:/sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-fr33z3}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-freezing}
      MYSQL_USER: ${MYSQL_USER:-freezing}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-zeer0}

  freezing-web:
    build: .
    container_name: freezing-web
    command: bafs-server
    ports:
      - "5000:8000"
    volumes:
      - ./data/cache:/data/cache
      - ./leaderboards:/data/leaderboards
      - ./data/sessions:/data/sessions
      - ./resources/docker/settings.cfg:/config/settings.cfg
    links:
      - freezing-db:freezing-db.container
    environment:
      VIRTUAL_HOST: ${FREEZING_WEB_FQDN}
      LETSENCRYPT_HOST: ${FREEZING_WEB_FQDN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      SQLALCHEMY_URL: ${SQLALCHEMY_URL:-mysql+pymysql://freezing:zeer0@freezing-db.container/freezing?charset=utf8mb4&binary_prefix=true}
      BEANSTALKD_HOST: beanstalkd.container
      BEANSTALKD_PORT: 11300
      STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}
      STRAVA_CLIENT_SECRET: ${STRAVA_CLIENT_SECRET}
      TEAMS: ${TEAMS}
      OBSERVER_TEAMS: ${OBSERVER_TEAMS}
      MAIN_TEAM: ${MAIN_TEAM}
      START_DATE: ${START_DATE}
      END_DATE: ${END_DATE}
      TIMEZONE: ${TIMEZONE:-America/New_York}
      COMPETITION_TITLE: ${COMPETITION_TITLE:-Freezing Saddles Local Dev}
