---
name: Build and Deploy

on:
  push:
    branches:
      - 'master'
      - 'github-actions-docker-build'  # until this is debugged, remove before merging

jobs:
  docker:
    uses: freezingsaddles/freezing-web/.github/workflows/build-docker.yml@1.4.7
    with:
      tag: latest
    secrets: inherit

  deploy:
    uses: appleboy/ssh-action@v1.1.0
    with:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USERNAME }}
      key: ${{ secrets.KEY }}
      port: ${{ secrets.PORT }}
      passphrase: ${{ secrets.PASSPHRASE }}
      script: |
        ls .ssh/authorized_keys
