---
name: Build Tag

on:
  push:
    tags:
      - '*' 

jobs:
  docker:
    uses: freezingsaddles/freezing-web/.github/workflows/build-docker.yml@1.4.12
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit
