---
name: Build

on: [push, pull_request]

jobs:
  docker:
    uses: freezingsaddles/freezing-web/.github/workflows/docker-build.yml@github-actions-docker-build
      with:
        tag: latest-actions-build
      secrets: inherit
