---
name: Build

on: [push, pull_request]

jobs:
  docker:
    uses: freezingsaddles/freezing-web/.github/workflows/build-docker.yml@1.4.2
    with:
      tag: latest-actions-build
    secrets: inherit
