---
name: Docker Build and Push

on: workflow_dispatch

inputs:

  org:
    description: 'Docker Hub organization'
    default: ${{ github.event.org.login }}

  repo:
    description: 'Docker Hub repository name'
    default: ${{ github.event.repository.name }}

  tag:
    description: 'tag for Docker container'
    default: ${{ GITHUB_SHA }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ org }}/${{ repo }}:${{ tag }}
