---
name: Docker Build and Push

on: 
  workflow_call:
    inputs:
      org:
        required: false
        description: 'Docker Hub organization'
        default: ${{ github.event.org.login }}
      repo:
        required: false
        description: 'Docker Hub repository name'
        default: ${{ github.event.repository.name }}
      tag:
        required: false
        description: 'tag for Docker container'
        default: ${{ GITHUB_SHA }}
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ org }}/${{ repo }}:${{ tag }}
