---
name: Lint

on: pull_request

jobs:
  # Thanks for the inspiration:
  # https://black.readthedocs.io/en/stable/integrations/github_actions.html
  python:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: black Lint
        uses: psf/black@24.1.1
      - name: isort Lint
        uses: isort/isort-action@v1
        with:
          requirements-files: "pyproject.toml"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          plugins: "flake8-pyproject"
      - name: lint - FawltyDeps
        uses: tweag/FawltyDeps-action@v0.2.0
        with:
          options: --detailed

  templates:
    name: Templates Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[dev]'
      - name: djlint Lint
        run: |
          djlint --check freezing/web/templates
      - name: PyMarkdown Lint
        run: |
          pymarkdown scan .
